In [1]:
import pandas as pd
import seaborn as sb

In [2]:
pwd

'C:\\Users\\sarah\\PycharmProjects\\Da_sima'

In [5]:
con = pd.read_csv("data\Connections.csv")

In [6]:
con.info()

<class 'pandas.DataFrame'>
RangeIndex: 1363 entries, 0 to 1362
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   First Name     1323 non-null   str
 1   Last Name      1323 non-null   str
 2   Email Address  18 non-null     str
 3   Company        1311 non-null   str
 4   Position       1309 non-null   str
 5   Connected On   1363 non-null   str
dtypes: str(6)
memory usage: 64.0 KB

In [7]:
con.head()

,First Name,Last Name,Email Address,Company,Position,Connected On
0,Liz,Dosovicky,NaN,WIZO Haifa Academy of Design and Education,Scheduling Manager,13-Nov-21
1,Ronen,"Tal-Botzer, Ph.D.",NaN,Evolution.Inc,Founder & CEO,11-Nov-21
2,Tamir,Berler,NaN,Self Employed,Consultant,04-Nov-21
3,Liav,Alter,NaN,The Hebrew University of Jerusalem,"Research Assistant, Data Scientist and Statist...",03-Nov-21
4,Ofir,Kimberg,NaN,aQurate Software Ltd.,Product Manager,03-Nov-21

In [21]:
con['Connected On']= pd.to_datetime(con['Connected On'],datetime = True)

TypeError: to_datetime() got an unexpected keyword argument 'datetime'

In [16]:
con.tail()

,First Name,Last Name,Email Address,Company,Position,Connected On
1358,Assaf,Levy Hasdai,NaN,EL AL Israel Airlines,Purser ( Inflight Service Manager ) and Head o...,<function to_datetime at 0x000001B8F570E480>
1359,Wendy,Zitzman,NaN,Private,Consultant,<function to_datetime at 0x000001B8F570E480>
1360,Alex,Tsimbler,NaN,CGI,Network Consultant,<function to_datetime at 0x000001B8F570E480>
1361,Ziv,Gilad,NaN,Self Employed Independent Consultant,"Microsoft Client Applications Professional, De...",<function to_datetime at 0x000001B8F570E480>
1362,Alon,Basis,NaN,Biohealing - Renovating Life,"Founder, CEO",<function to_datetime at 0x000001B8F570E480>

In [26]:
mask = con['Connected On'] >= '2021-01-01'
con[mask].head(5)

TypeError: '>=' not supported between instances of 'function' and 'str'