# PANDAS

WHAT IS PANDAS?


pandas is a Python package that provides fast, flexible, and expressive data structures designed to make working with "relational" or "labeled" data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python. Additionally, it has the broader goal of becoming the most powerful and flexible open source data analysis / manipulation tool available in any language. It is already well on its way towards this goal.

What Can Pandas Do?

Pandas can cleaning the data like delete or insert rows , 
contains wrong values, like empty or NULL values,
 data alignment,group by functionality,

Installation of Pandas

C:\Users\Your Name>pip install pandas

# Import Pandas Package

In [18]:
from IPython import display
#display.Image(filename="I stand with israel.png")
image_filename = "I stand with israel.png"
width = 100
height = 100
display.Image(filename="I stand with israel.png", width=width, height=height)

FileNotFoundError: [Errno 2] No such file or directory: 'I stand with israel.png'

In [ ]:
import pandas as pd

In [ ]:
#Pandas work with Series or Data frame
#A Pandas Series is like a column in a table.
#A Pandas DataFrame is a table with rows and columns.

In [ ]:
#all values in a series should have the same type. We can create a series by calling pandas.Series()
#Accessing Pandas Series by Using Index
#The values are labeled with their index number. The first value has index 0, the second value has index 1, etc.

In [ ]:
a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)

In [ ]:
type(a)

In [ ]:
type(myvar)

In [19]:
print(myvar[1])

NameError: name 'myvar' is not defined

In [20]:

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [21]:
type(myvar)

pandas.Series

In [22]:
type(a)

list

In [23]:
print(myvar["y"])

7

# Load Files Into a DataFrame

In [24]:
#A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [25]:
#Python method getcwd() returns current working directory of a process.
import os
os.getcwd()

'C:\\Users\\sarah\\PycharmProjects\\Da_sima\\Pandas'

In [26]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

### Load csv file

In [27]:
#Read data in the same directory that your python process is based or specify full path

In [28]:
df = pd.read_csv("customers.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'customers.csv'

In [ ]:
df

In [ ]:
df.head()

In [29]:
type(df)

NameError: name 'df' is not defined

In [30]:
df.columns

NameError: name 'df' is not defined

In [31]:
pd.set_option('display.max_columns',4)
pd.set_option('display.max_rows',4)

In [32]:
print(df)

NameError: name 'df' is not defined

In [33]:
products=pd.read_csv("Products.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Products.csv'

In [ ]:
products=pd.read_csv(r"C:\Users\Sima\Documents\Sima\DA\02-Python\Pandas Python\data\Products.csv")

In [ ]:
products

In [34]:
products.columns

NameError: name 'products' is not defined

In [35]:
type(products)

NameError: name 'products' is not defined

In [36]:
ct = pd.read_csv("data/Countries.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data/Countries.csv'

In [ ]:
ct

In [37]:
ct.head()

NameError: name 'ct' is not defined

In [38]:
ct.head(10)

NameError: name 'ct' is not defined

In [39]:
#Overriding Headers: Country Population Dataset

In [40]:
ct = pd.read_csv("data/Countries.csv",names=["yy","count","pop","world pop"])

FileNotFoundError: [Errno 2] No such file or directory: 'data/Countries.csv'

In [ ]:
ct

In [41]:
#header=0: This parameter indicates that the header (column names) is in the 0th (first) row of the CSV file.

In [42]:
ct = pd.read_csv("data/Countries.csv",names=["yy","count","pop","world pop"],header=0)

FileNotFoundError: [Errno 2] No such file or directory: 'data/Countries.csv'

In [ ]:
ct

In [43]:
#Import specific columns
ct = pd.read_csv("data/Countries.csv",names=["year","country","population"])

FileNotFoundError: [Errno 2] No such file or directory: 'data/Countries.csv'

In [ ]:
ct.head()

In [44]:
newname = ["year","country","population"]
ct = pd.read_csv("data/Countries.csv",names=newname)

FileNotFoundError: [Errno 2] No such file or directory: 'data/Countries.csv'

In [ ]:
ct.head()

In [45]:
newname = ["yy","country","population"]
ct = pd.read_csv("data/Countries.csv",names=newname,header=0,usecols=newname)

FileNotFoundError: [Errno 2] No such file or directory: 'data/Countries.csv'

In [ ]:
ct.head()

### Seaborn Datasets

In [46]:
#Seaborn is a library for making statistical graphics in Python.

In [47]:
import seaborn as sb

In [48]:
sb.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [49]:
titanic = sb.load_dataset('titanic')

In [50]:
titanic

     survived  pclass  ... alive  alone
0           0       3  ...    no  False
1           1       1  ...   yes  False
..        ...     ...  ...   ...    ...
889         1       1  ...   yes   True
890         0       3  ...    no   True

[891 rows x 15 columns]

In [51]:
diamonds =sb.load_dataset('diamonds')

In [52]:
diamonds

       carat      cut  ...     y     z
0       0.23    Ideal  ...  3.98  2.43
1       0.21  Premium  ...  3.84  2.31
...      ...      ...  ...   ...   ...
53938   0.86  Premium  ...  6.12  3.74
53939   0.75    Ideal  ...  5.87  3.64

[53940 rows x 10 columns]

In [53]:
tips =sb.load_dataset('tips')

In [54]:
tips

     total_bill   tip  ...    time size
0         16.99  1.01  ...  Dinner    2
1         10.34  1.66  ...  Dinner    3
..          ...   ...  ...     ...  ...
242       17.82  1.75  ...  Dinner    2
243       18.78  3.00  ...  Dinner    2

[244 rows x 7 columns]

### Read Excel files

In [55]:
#Import Data from Excel file
#pip install xlrd
#pip install --upgrade xlrd
#pip install openpyxl
#import xlrd
#import pandas as pd

In [56]:
orders = pd.read_excel('data\Orders.xlsx')
orders.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data\\Orders.xlsx'

### Connection to database mssql

In [60]:
%pip install pyodbc sqlalchemy
# %pwd

Requirement already satisfied: pyodbc in c:\users\sarah\pycharmprojects\pythonproject3\venv\lib\site-packages (5.3.0)
Collecting sqlalchemy
  Obtaining dependency information for sqlalchemy from https://files.pythonhosted.org/packages/58/d5/dd767277f6feef12d05651538f280277e661698f617fa4d086cce6055416/sqlalchemy-2.0.48-cp311-cp311-win_amd64.whl.metadata
  Downloading sqlalchemy-2.0.48-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Obtaining dependency information for greenlet>=1 from https://files.pythonhosted.org/packages/f1/3a/efb2cf697fbccdf75b24e2c18025e7dfa54c4f31fab75c51d0fe79942cef/greenlet-3.3.2-cp311-cp311-win_amd64.whl.metadata
  Downloading greenlet-3.3.2-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sarah\pycharmprojects\pythonproject3\venv\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.48-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   - -------------------------------------- 0.1/2.1 MB 825.8 kB/s eta 0:00:03
   -- ------------------------------------- 0.1/2.1 MB 939.4 kB/s eta 0:00:03
   ---- ----------------------------------- 0.2/2.1 MB 1.4 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.1 MB 2.2 MB/s eta 0:00:01
   ---------- ----------------------------- 0.6/2.1 MB 2.2 MB/s eta 0:00:01
   ------------------ --------------------- 1.0/2.1 MB 3.2 MB/s eta 0:00:01
   ---------------------- ----------------- 1.2/2.1 MB 3.5 MB/s eta 0:00:01
   ---------------------------- ----------- 1.5/2.1 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 1.7/2.1 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 2.1/2.1 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.0 MB/s eta 0:00:00
Downloading greenlet-3.3.2-cp311-cp311-win_amd64.whl (230 kB)
   ---------------------------------------- 0.0/230.4 kB ? eta -:--:--
   ---------------------------------------- 230.4/230.4 kB 6.9 MB/s eta 0:00:00
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.3.2 sqlalchemy-2.0.48
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: C:\Users\sarah\PycharmProjects\pythonProject3\venv\Scripts\python.exe -m pip install --upgrade pip

In [ ]:
#pip install pyodbc
#pip install SQLAlchemy
#import pyodbc
#con = pyodbc.connect(
#  host ="localhost",
#  user = "yourusername",
#  password = "yourpassword",
#  database ="mydatabase"
#)

#To find the ODBC driver name that you can use to export data to Pandas from SQL Server, you can check your ODBC Data Source Administrator. Follow these steps:
#On Windows:
#1.Open the Start menu and search for "ODBC Data Sources" or "ODBC Data Source Administrator."
#2.go to the "Drivers" tab. Here you'll find a list of installed ODBC drivers with their names.
#To retrieve the server name (instance name) run this query from sql server :SELECT @@SERVERNAME

In [64]:
import pyodbc
from sqlalchemy import create_engine

driver = "SQL Server"
server = "Sarah-Laptop\MSSQLSERVER22"
database = "Northwind"
trusted_connection = "yes"
conn =pyodbc.connect(f'Driver={{driver}};'
                     f'Server={server};'
                     f'Database={database};'
                     f'Trusted_Connection=yes;')

connection_string = f'mssql+pyodbc://{server}/{database}?trusted_connection={trusted_connection}&driver={driver}'
engine = create_engine(connection_string)

SyntaxError: f-string expression part cannot include a backslash (3718509429.py, line 11)

#Connect to SQL Server Database with SQLAlchemy:
#import pyodbc
#from sqlalchemy import create_engine
#driver = 'SQL Server Native Client 11.0'
#server = 'localhost'
#database = 'Northwind'
#trusted_connection = 'yes'
#connection_string = f'mssql+pyodbc://{server}/{database}?trusted_connection={trusted_connection}&driver={driver}'
#engine = create_engine(connection_string)

In [58]:
df = pd.read_sql("select * from Products",conn)

C:\Users\sarah\AppData\Local\Temp\ipykernel_5864\500196871.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("select * from Products",conn)

In [ ]:
df

## General information

In [ ]:
#df.shape
#df.head()
#df.tail()
#df.info()
#df.describe()

In [ ]:
products

In [ ]:
products.columns

In [ ]:
products.values

In [ ]:
products.shape

In [ ]:
len(products)

In [ ]:
#columns* rows
products.size

In [ ]:
products.info()

In [ ]:
products.head()

In [ ]:
products.head(5)

In [ ]:
products.tail(5)

### Display specific columns

In [ ]:
#2 Options to select columns
#df.column
#df['column']

In [ ]:
products["ProductName"].head()

In [ ]:
products.UnitPrice.head()

In [ ]:
price =products.UnitPrice

In [ ]:
price

In [ ]:
#series 
type(price)

In [ ]:
price.head()

In [ ]:
price.shape

In [ ]:
price.values

In [ ]:
price.describe()

In [ ]:
products.head()

In [ ]:
products["ProductName"].head()

In [ ]:
products["ProductName"].describe()

In [ ]:
type(products["ProductName"])

In [ ]:
products[["ProductName","UnitPrice"]].head()

In [ ]:
type(products)

In [ ]:
type(products["ProductName"].head())

In [ ]:
#to_frame --Convert Series to DataFrame.
# or use [[]]
# DataFrame objects can have different data types. 
#Series --– All elements must be of same data type.

In [ ]:
products["ProductName"].to_frame()

In [ ]:
type(products["ProductName"].to_frame().head())

In [ ]:
products[["ProductName"]].head()

In [ ]:
type(products[["ProductName"]].head())

In [ ]:
type(products[["UnitPrice"]])

In [ ]:
#Calculation -- + - * /

In [ ]:
products[["UnitPrice"]].head(5)+10

In [ ]:
(products[["UnitPrice"]]-10).head(5)

In [ ]:
products[["UnitPrice"]].head(5)-10

In [ ]:
products[["UnitPrice"]].head(5)*1.17

In [ ]:
column = ["ProductID","ProductName","UnitPrice"]
products[column].head()

### Concatenation

In [ ]:
(products["ProductName"].head(5)+' '+str(products["UnitPrice"].head(5))).to_frame()

In [ ]:
products["ProductName"].head(5) + ' ' + products["UnitPrice"].astype(str).head(5)

In [ ]:
(products["ProductName"].head(5) + ' ' + products["UnitPrice"].head(5).astype(str)).to_frame()

In [ ]:
a

In [ ]:
type(a)

In [ ]:
df = pd.read_sql("select LastName,FirstName from Employees",conn)

In [ ]:
df

In [ ]:
type(df)

In [ ]:
df[["LastName","FirstName"]].head(3)

In [ ]:
(df["LastName"]+' '+df["FirstName"]).to_frame()

### Rename Columns

In [ ]:

# * List =   [] read/write
# * Tuples = () read only
# * Dictionaries{key:value,key:value}

In [ ]:
df[["LastName","FirstName"]].rename(columns = {"LastName":"LName","FirstName":"FName"})

In [ ]:
(df["LastName"]+' '+df["FirstName"]).to_frame(name="FullName")

### Distinct ---drop_duplicates

In [ ]:
df_loc = pd.read_sql("select Country, City from employees",conn)

In [ ]:
df_loc

In [ ]:
df_loc.drop_duplicates()

In [ ]:
df_loc[["Country"]].drop_duplicates()

In [ ]:
df_loc

### Add New column

In [ ]:
products.head(5)

In [ ]:
products["After Tax"] = products["UnitPrice"]*1.17

In [ ]:
products.head()

In [ ]:
products.assign(Total=products["UnitPrice"]*1.17).head(5)

In [ ]:
products.head()

### Add column to specific location

In [ ]:
products.insert(3,'Total',products["UnitPrice"]*1.17)

In [ ]:
products.head()

In [ ]:
products.assign(Discount=products["UnitPrice"]*0.1,
                 AfterDiscount=products["UnitPrice"]-products["UnitPrice"]*0.1).head()

In [ ]:
products.head()

In [ ]:
products.drop(columns ="Total")

In [ ]:
products.head()

In [ ]:
products.drop(["Total"],axis=1).head()

In [ ]:
products.head()

### pop out a column from the dataframe

In [ ]:
#df.pop(column)
#del df[column]

In [ ]:
#Return item and drop from frame.
products.pop("Total")

In [ ]:
products.head()

In [ ]:
products["Total"]=products["UnitPrice"]*1.17

In [ ]:
products.head()

In [ ]:
del products["Total"]

In [ ]:
products.head()

In [ ]:
titanic.head()

In [ ]:
#pandas.DataFrame.drop

In [ ]:
#Remove rows or columns by specifying label names and corresponding axis, or by specifying directly index or column names.
drop_row=titanic.drop(0)

In [ ]:
drop_row.head()

In [ ]:
#axis = 1 or columns
drop_col=titanic.drop(labels="deck",axis=1)

In [ ]:
drop_col.head()

In [ ]:
drop_col=titanic.drop(labels=["deck","who","embarked"],axis="columns")

In [ ]:
drop_col.head()

In [ ]:
#To cahnge original dataframe

In [ ]:
titanic

In [ ]:
titanic.drop(labels="deck",axis=1, inplace=True)

In [ ]:
titanic.head()

In [ ]:
#short way drop columns

In [ ]:
titanic.drop(columns=["sibsp","parch","who"])

### replace method

In [ ]:
titanic["sex"].replace("female","F")

In [ ]:
titanic["sex"].replace(["female","male"],["f","m"])

In [ ]:
titanic

In [ ]:
titanic["sex"].replace(["female","male"],["f","m"],inplace=True)

In [ ]:
titanic

In [ ]:
titanic.info()